"""
Load modes from saved prior computations
"""

from fibermode import StepIndex

# load the following file in ../../outputs folder generated by guidedmodes.py:
filenameprefix = 'my_tmp_output'
fiber = StepIndex(fromfile=filenameprefix)
betas2, Y2, n2i = fiber.loadmodes(filenameprefix + '_mde.npz')

# draw the loaded modes (use "netgen loadmodes.py" on the shell)
Y2.draw()
